//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELBancoPichincha
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT()
        {
            this.MOVEMENT = new HashSet<MOVEMENT>();
        }
    
        public int ID_ACCOUNT { get; set; }
        [Required]
        public int ID_CUSTOMER { get; set; }
        [Required]
        public string NUMBER { get; set; }
        [Required]
        public string TYPE { get; set; }
        [Required]
        public decimal INITIAL_BALANCE { get; set; }
        [Required]
        public string STATE { get; set; }
        [Required]
        public Nullable<decimal> LIMIT { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVEMENT> MOVEMENT { get; set; }
    }
}
